services:
  - type: web
    name: takaful-test-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py createsu
    startCommand: gunicorn takaful.wsgi:application --preload

