services:
  - type: web
    name: takaful-test-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
    startCommand: gunicorn takaful.wsgi:application --preload

